# -*- coding: utf-8 -*-
"""House_Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c5ic0TDBGl3IL-Dz1BQcuF8MJoImwWlt
"""

#Read the dataset
import pandas as pd
data = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vTe0nGcSaHE12JTJuOtSF0uBp114M8NXP12FL2LJCY4JcGAN4WQcda5EahhK73YLIBmPZPyrH-k0i_H/pub?output=csv")

#select the target and independent variables
independent_variables = data.columns
independent_variables = independent_variables.delete(0)
X = data[independent_variables]
Y = data["price"]
#fit the model
import sklearn.linear_model as lm
lr = lm.LinearRegression()
lr.fit(X,Y)

#Predict Price using LinearRegression Model
user_info = {}
for feature in independent_variables:
  temp = input("Enter " + feature + ": ")
  user_info[feature] = temp
  user_info_df = pd.DataFrame(data=user_info,index=[0],columns=independent_variables)
price = lr.predict(user_info_df)
print(int(round(price[0])))

